# Generated by Django 5.1.4 on 2025-01-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_blog_image.jpg', upload_to='blog_images/'),
        ),
    ]
